{
   "checksum": "1bfcf24fd60969320f6aac12b04195b3",
   "roots": {
      "bookmark_bar": {
         "children": [ {
            "children": [ {
               "date_added": "12977516382425159",
               "id": "486",
               "name": "Member Universities",
               "type": "url",
               "url": "http://www.ucar.edu/governance/members/institutions.shtml"
            }, {
               "date_added": "12977516382425251",
               "id": "487",
               "name": "\u963F\u8054\u914Bweather",
               "type": "url",
               "url": "http://www.ncms.ae/english/"
            }, {
               "date_added": "12977516382425336",
               "id": "488",
               "name": "\u9999\u6E2F\u4E2D\u6587\u5927\u5B66",
               "type": "url",
               "url": "http://translate.itsc.cuhk.edu.hk/gb/www.cuhk.edu.hk/v6/b5/"
            }, {
               "date_added": "12977516382425430",
               "id": "489",
               "name": "Atmospheric Sciences and Meteorology Colleges and Atmospheric Sciences and Meteorology Schools | USCS",
               "type": "url",
               "url": "http://www.uscollegesearch.org/atmospheric-sciences-and-meteorology-colleges.html"
            }, {
               "date_added": "12977516382425648",
               "id": "490",
               "name": "NRC University Rankings 2011 | Online University Rankings",
               "type": "url",
               "url": "http://onlineuniversityrankings.org/rankings-by-provider/nrc-university-rankings-2010/"
            }, {
               "date_added": "12977516382425751",
               "id": "491",
               "name": "NRC 2010 \u6D77\u6D0B\u4E0E\u5927\u6C14\u79D1\u5B66(Oceanography, Atmospheric Sciences)\u6392\u540D Basic HTML View - \u98DE\u8DC3\u7F51 - \u7F8E\u56FD\u7559\u5B66\u6307\u5357",
               "type": "url",
               "url": "http://www.giantleap.us/rank/listBasicHTML/NRC_MarineSci_Atmos_2010/MarineSci,Atmos/0.htm"
            } ],
            "date_added": "12977516382348868",
            "date_modified": "12979060258889838",
            "id": "4",
            "name": "applicate",
            "type": "folder"
         }, {
            "children": [ {
               "date_added": "12977516382423962",
               "id": "476",
               "name": "CNKI\u4E2D\u56FD\u77E5\u7F51-\u6C49\u8BED\u8BCD\u5178\u5728\u7EBF",
               "type": "url",
               "url": "http://cdict.cnki.net/"
            }, {
               "date_added": "12977516382424070",
               "id": "477",
               "name": "\u5728\u7EBF\u65B0\u534E\u5B57\u5178",
               "type": "url",
               "url": "http://xh.5156edu.com/"
            }, {
               "date_added": "12977516382424156",
               "id": "478",
               "name": "\u6C49\u5178 zdic.net",
               "type": "url",
               "url": "http://www.zdic.net/"
            }, {
               "date_added": "12977516382424249",
               "id": "479",
               "name": "\u7FFB\u8BD1\u8BCD\u5178-\u5728\u7EBF\u8BCD\u5178\uFF1A\u5728\u4E2D\u56FD\u6700\u5927\u7FFB\u8BD1\u8BED\u6599\u5E93\uFF08\u4E2D\u56FD\u8BD1\u5178@\u4E2D\u56FD\u5728\u7EBF\u7FFB\u8BD1\u7F51\uFF09\u67E5\u8BE2,",
               "type": "url",
               "url": "http://www.tdict.com/default.asp"
            }, {
               "date_added": "12977516382424404",
               "id": "480",
               "name": "Dict.CN \u6D77\u8BCD_\u5728\u7EBF\u8BCD\u5178_\u5728\u7EBF\u7FFB\u8BD1_\u5728\u7EBF\u82F1\u8BED\u5B66\u4E60_\u4E2D\u56FD\u6700\u5927\u6700\u4E13\u4E1A\u7684\u5728\u7EBF\u8BCD\u5178",
               "type": "url",
               "url": "http://dict.cn/"
            }, {
               "date_added": "12977516382424547",
               "id": "481",
               "name": "Google \u5B57\u5178",
               "type": "url",
               "url": "http://www.google.com.hk/dictionary"
            }, {
               "date_added": "12977516382424641",
               "id": "482",
               "name": "Merriam-Webster Online",
               "type": "url",
               "url": "http://www.merriam-webster.com/"
            }, {
               "date_added": "12977516382424738",
               "id": "483",
               "name": "Urban Dictionary, January 6: don't take this the wrong way, but",
               "type": "url",
               "url": "http://www.urbandictionary.com/"
            }, {
               "date_added": "12977516382424864",
               "id": "484",
               "name": "\u7528\u624B\u673A\u7F16\u7A0B`\u60F3\u5B66python\u7684\u8FDB\u6765\u554A\uFF01\uFF01python\u8F6F\u4EF6+\u6559\u7A0B - \u8BFA\u57FA\u4E9A5320XM\u8BBA\u575B - \u585E\u73ED\u667A\u80FD\u624B\u673A\u8BBA\u575B-Symbian\u7CFB\u7EDF\u667A\u80FD\u624B\u673A\u4E2D\u6587\u8BBA\u575B",
               "type": "url",
               "url": "http://bbs.dospy.com/thread-3776136-1-1.html"
            }, {
               "date_added": "12977516382425034",
            